dist: bionic
language: cpp
install:
  - pip install --user conan cmake
jobs:
  include:
    - os: linux
      dist: bionic
      compiler: gcc
      env:
        - GCC_VER="10"
        - MATRIX_EVAL="CC=gcc-${GCC_VER} && CXX=g++-${GCC_VER}"
        - BUILD_CONFIGURATION=Debug
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            # I couldn't get ${GCC_VER} in here successfully
            - gcc-10
            - g++-10
      after_script:
        - bash <(curl -s https://codecov.io/bash) -x /usr/bin/gcov-${GCC_VER}

before_script:
  - eval "${MATRIX_EVAL}"

script:
  - mkdir build && cd build
  - cmake -D ENABLE_COVERAGE:BOOL=TRUE -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION ../
  - cmake --build . --target tests -- -j 2
  - ctest -j2



